[[task]]
name = "signal desktop"
path = "/nix/store/8x9r22b73lcvwqyq538951fdaizpcf4b-signal-desktop-5.54.0/bin/signal-desktop"
arguments = ["arg1", "arg2"]
non_error_codes = [3, 1, -2]
restart_condition = "OnError"


