[[task]]
name = "firefox"
path = "/usr/bin/firefox"
arguments = ["arg1", "arg2"]
non_error_codes = [3, 1, -2]
restart_condition = "OnError"


[[task]]
name = "thunderbird"
path = "/usr/bin/thunderbird"
arguments = ["arg1", "arg2"]
non_error_codes = [3, 1, -2]
restart_condition = "Always"



[[task]]
name = "nautilus"
path = "/usr/bin/nautilus"
arguments = ["arg1", "arg2"]
non_error_codes = [3, 1, -2]
restart_condition = "Never"
